jeka.classpath=../../.jeka-work/jeka-src-classes
jeka.java.version=23

@project=on
@project.pack.jarType=REGULAR
@project.pack.detectMainClass=true

@javafx=on
@javafx.version=23

@bundle=on
@bundle.projectPack=true
@bundle.jpackage.options.mac.--type=app-image
